# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_week', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(53), django.core.validators.MinValueValidator(1)])),
                ('year', models.SmallIntegerField()),
                ('num_bookings', models.SmallIntegerField()),
                ('facility', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together=set([('calendar_week', 'year', 'facility')]),
        ),
    ]
