# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170329_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='num_bookings',
            new_name='bookings',
        ),
    ]
