# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170329_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='bookings',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='calendar_week',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(53), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
