# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170329_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='bookings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
