# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170329_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='calendar_week',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
